In [ ]:
#This program detects if an email is spam or not

In [16]:
#import libraries

import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [55]:
import pandas as pd

# Try different encodings until you find the correct one
encodings_to_try = ['utf-8', 'latin-1', 'ISO-8859-1', 'utf-16']

file_path = 'D:\\Anju\\Projects\\Spam mail detection\\spam.csv'

for encoding in encodings_to_try:
    try:
        df = pd.read_csv(file_path, encoding=encoding, delimiter=',')
        break  # If successful, exit the loop
    except UnicodeDecodeError:
        continue  # If decoding fails, try the next encoding

# Display the contents of the DataFrame
df

Spa                                               text Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [56]:
# drop the variables
df = df.iloc[:, :2]
df

Spa                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [57]:
# Assuming df is your DataFrame with a "Spa" column
df = df.copy()  # Create a copy of the DataFrame
df['Spamm'] = df['Spa'].apply(lambda x: 0 if x == 'ham' else 1)
df

Spa                                               text  Spamm
0      ham  Go until jurong point, crazy.. Available only ...      0
1      ham                      Ok lar... Joking wif u oni...      0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3      ham  U dun say so early hor... U c already then say...      0
4      ham  Nah I don't think he goes to usf, he lives aro...      0
...    ...                                                ...    ...
5567  spam  This is the 2nd time we have tried 2 contact u...      1
5568   ham              Will Ì_ b going to esplanade fr home?      0
5569   ham  Pity, * was in mood for that. So...any other s...      0
5570   ham  The guy did some bitching but I acted like i'd...      0
5571   ham                         Rofl. Its true to its name      0

[5572 rows x 3 columns]

In [58]:
#Get the shape (Get the number of raws and columns)

df.shape


(5572, 3)

In [61]:
# drop the first column (index 0)
df = df.drop(columns=df.columns[:1])
df

text  Spamm
0     Go until jurong point, crazy.. Available only ...      0
1                         Ok lar... Joking wif u oni...      0
2     Free entry in 2 a wkly comp to win FA Cup fina...      1
3     U dun say so early hor... U c already then say...      0
4     Nah I don't think he goes to usf, he lives aro...      0
...                                                 ...    ...
5567  This is the 2nd time we have tried 2 contact u...      1
5568              Will Ì_ b going to esplanade fr home?      0
5569  Pity, * was in mood for that. So...any other s...      0
5570  The guy did some bitching but I acted like i'd...      0
5571                         Rofl. Its true to its name      0

[5572 rows x 2 columns]

In [62]:
#Get the column names

df.columns

Index(['text', 'Spamm'], dtype='object')

In [63]:
#Check for duplicates and remove them
df.drop_duplicates(inplace = True)

In [64]:
#Get the new shape of the dataset
df.shape

(5169, 2)

In [65]:
#show the number of missing data(NAN, NaN, na) for each column
df.isnull().sum()

text     0
Spamm    0
dtype: int64

In [66]:
#Download stopwords package

nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jibin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [76]:
import string
from nltk.corpus import stopwords

# Create a function to process the text
def process_text(text): 
    # Remove punctuation from the text
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    # Remove stopwords
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    # Return a list of clean text words
    return clean_words

# Apply the process_text function to the 'text' column
df['text'].head().apply(process_text)


0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: text, dtype: object

In [77]:
#convert a collection of text to a matriz of tokens

from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [79]:
#Split the data into 80% and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(messages_bow, df['Spamm'], test_size=0.20, random_state=0)


In [83]:
#Get the shape of messages_bow

messages_bow.shape

(5169, 11304)

In [85]:
#Create and train the Naive Bayes Classifier(multyinomial naive calssifier which is suitable for clasification with descrete features)

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train,Y_train)

In [86]:
#print the predictions
print(classifier.predict(X_train))

[0 0 0 ... 0 0 0]


In [87]:
#print the actual values

print(Y_train.values)

[0 0 0 ... 0 0 0]


In [90]:
#Evaluate the model on training dataset

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(Y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3631
           1       0.98      0.98      0.98       504

    accuracy                           1.00      4135
   macro avg       0.99      0.99      0.99      4135
weighted avg       1.00      1.00      1.00      4135



In [92]:

print('confusion_matrix: \n', confusion_matrix(Y_train, pred))

confusion_matrix: 
 [[3623    8]
 [  11  493]]


In [93]:
print('Accuracy: ', accuracy_score(Y_train, pred))

Accuracy:  0.9954050785973397


In [94]:
#print the predictions
print(classifier.predict(X_test))

#print the actual values
print(Y_test.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [95]:
#Evaluate the model on test dataset

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(Y_test, pred))

print('confusion_matrix: \n', confusion_matrix(Y_test, pred))

print('Accuracy: ', accuracy_score(Y_test, pred))

              precision    recall  f1-score   support

           0       0.99      0.96      0.97       885
           1       0.80      0.93      0.86       149

    accuracy                           0.96      1034
   macro avg       0.89      0.94      0.92      1034
weighted avg       0.96      0.96      0.96      1034

confusion_matrix: 
 [[850  35]
 [ 11 138]]
Accuracy:  0.9555125725338491
